/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type { BaseContract, BigNumberish, BytesLike, FunctionFragment, Result, Interface, EventFragment, AddressLike, ContractRunner, ContractMethod, Listener } from "ethers"
import type { TypedContractEvent, TypedDeferredTopicFilter, TypedEventLog, TypedLogDescription, TypedListener, TypedContractMethod } from "./common.js"
  

  export interface FreelanceEscrowInterface extends Interface {
    getFunction(nameOrSignature: "acceptJob" | "addMilestone" | "approveMilestone" | "cancelJob" | "concludeJob" | "createJob" | "getEscrowBalance" | "getMilestones" | "jobCounter" | "jobs" | "raiseDispute" | "resolveDispute" | "tipFreelancer"): FunctionFragment;

    getEvent(nameOrSignatureOrTopic: "DisputeRaised" | "DisputeResolved" | "JobCancelled" | "JobConcludedEarly" | "JobCreated" | "MilestoneAdded" | "MilestoneApproved" | "TipSent" | "WorkStarted"): EventFragment;

    encodeFunctionData(functionFragment: 'acceptJob', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'addMilestone', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'approveMilestone', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'cancelJob', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'concludeJob', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'createJob', values: [AddressLike, BigNumberish[]]): string;
encodeFunctionData(functionFragment: 'getEscrowBalance', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'getMilestones', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'jobCounter', values?: undefined): string;
encodeFunctionData(functionFragment: 'jobs', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'raiseDispute', values: [BigNumberish]): string;
encodeFunctionData(functionFragment: 'resolveDispute', values: [BigNumberish, BigNumberish, BigNumberish]): string;
encodeFunctionData(functionFragment: 'tipFreelancer', values: [BigNumberish]): string;

    decodeFunctionResult(functionFragment: 'acceptJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'addMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'approveMilestone', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'cancelJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'concludeJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'createJob', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getEscrowBalance', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'getMilestones', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jobCounter', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'jobs', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'raiseDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'resolveDispute', data: BytesLike): Result;
decodeFunctionResult(functionFragment: 'tipFreelancer', data: BytesLike): Result;
  }

  
    export namespace DisputeRaisedEvent {
      export type InputTuple = [jobId: BigNumberish, raisedBy: AddressLike];
      export type OutputTuple = [jobId: bigint, raisedBy: string];
      export interface OutputObject {jobId: bigint, raisedBy: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace DisputeResolvedEvent {
      export type InputTuple = [jobId: BigNumberish, clientAmount: BigNumberish, freelancerAmount: BigNumberish];
      export type OutputTuple = [jobId: bigint, clientAmount: bigint, freelancerAmount: bigint];
      export interface OutputObject {jobId: bigint, clientAmount: bigint, freelancerAmount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobCancelledEvent {
      export type InputTuple = [jobId: BigNumberish];
      export type OutputTuple = [jobId: bigint];
      export interface OutputObject {jobId: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobConcludedEarlyEvent {
      export type InputTuple = [jobId: BigNumberish, amountRefundedToClient: BigNumberish];
      export type OutputTuple = [jobId: bigint, amountRefundedToClient: bigint];
      export interface OutputObject {jobId: bigint, amountRefundedToClient: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace JobCreatedEvent {
      export type InputTuple = [jobId: BigNumberish, client: AddressLike, totalAmount: BigNumberish, milestones: BigNumberish];
      export type OutputTuple = [jobId: bigint, client: string, totalAmount: bigint, milestones: bigint];
      export interface OutputObject {jobId: bigint, client: string, totalAmount: bigint, milestones: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneAddedEvent {
      export type InputTuple = [jobId: BigNumberish, amountAdded: BigNumberish, newTotalMilestones: BigNumberish];
      export type OutputTuple = [jobId: bigint, amountAdded: bigint, newTotalMilestones: bigint];
      export interface OutputObject {jobId: bigint, amountAdded: bigint, newTotalMilestones: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace MilestoneApprovedEvent {
      export type InputTuple = [jobId: BigNumberish, milestoneNumber: BigNumberish, amountReleased: BigNumberish];
      export type OutputTuple = [jobId: bigint, milestoneNumber: bigint, amountReleased: bigint];
      export interface OutputObject {jobId: bigint, milestoneNumber: bigint, amountReleased: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace TipSentEvent {
      export type InputTuple = [jobId: BigNumberish, sender: AddressLike, amount: BigNumberish];
      export type OutputTuple = [jobId: bigint, sender: string, amount: bigint];
      export interface OutputObject {jobId: bigint, sender: string, amount: bigint };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

    export namespace WorkStartedEvent {
      export type InputTuple = [jobId: BigNumberish, freelancer: AddressLike];
      export type OutputTuple = [jobId: bigint, freelancer: string];
      export interface OutputObject {jobId: bigint, freelancer: string };
      export type Event = TypedContractEvent<InputTuple, OutputTuple, OutputObject>
      export type Filter = TypedDeferredTopicFilter<Event>
      export type Log = TypedEventLog<Event>
      export type LogDescription = TypedLogDescription<Event>
    }

  

  export interface FreelanceEscrow extends BaseContract {
    
    connect(runner?: ContractRunner | null): FreelanceEscrow;
    waitForDeployment(): Promise<this>;

    interface: FreelanceEscrowInterface;

    
  queryFilter<TCEvent extends TypedContractEvent>(
    event: TCEvent,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined,
  ): Promise<Array<TypedEventLog<TCEvent>>>
  queryFilter<TCEvent extends TypedContractEvent>(
    filter: TypedDeferredTopicFilter<TCEvent>,
    fromBlockOrBlockhash?: string | number | undefined,
    toBlock?: string | number | undefined
  ): Promise<Array<TypedEventLog<TCEvent>>>;

  on<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  on<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>
  
  once<TCEvent extends TypedContractEvent>(event: TCEvent, listener: TypedListener<TCEvent>): Promise<this>
  once<TCEvent extends TypedContractEvent>(filter: TypedDeferredTopicFilter<TCEvent>, listener: TypedListener<TCEvent>): Promise<this>

  listeners<TCEvent extends TypedContractEvent>(
    event: TCEvent
  ): Promise<Array<TypedListener<TCEvent>>>;
  listeners(eventName?: string): Promise<Array<Listener>>
  removeAllListeners<TCEvent extends TypedContractEvent>(event?: TCEvent): Promise<this>


    
    
    acceptJob: TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    addMilestone: TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'payable'
    >
    

    
    approveMilestone: TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    cancelJob: TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    concludeJob: TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    createJob: TypedContractMethod<
      [_arbiter: AddressLike, _milestoneAmounts: BigNumberish[], ],
      [void],
      'payable'
    >
    

    
    getEscrowBalance: TypedContractMethod<
      [_jobId: BigNumberish, ],
      [bigint],
      'view'
    >
    

    
    getMilestones: TypedContractMethod<
      [_jobId: BigNumberish, ],
      [bigint[]],
      'view'
    >
    

    
    jobCounter: TypedContractMethod<
      [],
      [bigint],
      'view'
    >
    

    
    jobs: TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint] & {id: bigint, client: string, freelancer: string, arbiter: string, completedMilestones: bigint, originalMilestones: bigint, escrowBalance: bigint, state: bigint }],
      'view'
    >
    

    
    raiseDispute: TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    resolveDispute: TypedContractMethod<
      [_jobId: BigNumberish, clientAmount: BigNumberish, freelancerAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >
    

    
    tipFreelancer: TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'payable'
    >
    


    getFunction<T extends ContractMethod = ContractMethod>(key: string | FunctionFragment): T;

    getFunction(nameOrSignature: 'acceptJob'): TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'addMilestone'): TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'approveMilestone'): TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'cancelJob'): TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'concludeJob'): TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'createJob'): TypedContractMethod<
      [_arbiter: AddressLike, _milestoneAmounts: BigNumberish[], ],
      [void],
      'payable'
    >;
getFunction(nameOrSignature: 'getEscrowBalance'): TypedContractMethod<
      [_jobId: BigNumberish, ],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'getMilestones'): TypedContractMethod<
      [_jobId: BigNumberish, ],
      [bigint[]],
      'view'
    >;
getFunction(nameOrSignature: 'jobCounter'): TypedContractMethod<
      [],
      [bigint],
      'view'
    >;
getFunction(nameOrSignature: 'jobs'): TypedContractMethod<
      [arg0: BigNumberish, ],
      [[bigint, string, string, string, bigint, bigint, bigint, bigint] & {id: bigint, client: string, freelancer: string, arbiter: string, completedMilestones: bigint, originalMilestones: bigint, escrowBalance: bigint, state: bigint }],
      'view'
    >;
getFunction(nameOrSignature: 'raiseDispute'): TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'resolveDispute'): TypedContractMethod<
      [_jobId: BigNumberish, clientAmount: BigNumberish, freelancerAmount: BigNumberish, ],
      [void],
      'nonpayable'
    >;
getFunction(nameOrSignature: 'tipFreelancer'): TypedContractMethod<
      [_jobId: BigNumberish, ],
      [void],
      'payable'
    >;

    getEvent(key: 'DisputeRaised'): TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
getEvent(key: 'DisputeResolved'): TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
getEvent(key: 'JobCancelled'): TypedContractEvent<JobCancelledEvent.InputTuple, JobCancelledEvent.OutputTuple, JobCancelledEvent.OutputObject>;
getEvent(key: 'JobConcludedEarly'): TypedContractEvent<JobConcludedEarlyEvent.InputTuple, JobConcludedEarlyEvent.OutputTuple, JobConcludedEarlyEvent.OutputObject>;
getEvent(key: 'JobCreated'): TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
getEvent(key: 'MilestoneAdded'): TypedContractEvent<MilestoneAddedEvent.InputTuple, MilestoneAddedEvent.OutputTuple, MilestoneAddedEvent.OutputObject>;
getEvent(key: 'MilestoneApproved'): TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
getEvent(key: 'TipSent'): TypedContractEvent<TipSentEvent.InputTuple, TipSentEvent.OutputTuple, TipSentEvent.OutputObject>;
getEvent(key: 'WorkStarted'): TypedContractEvent<WorkStartedEvent.InputTuple, WorkStartedEvent.OutputTuple, WorkStartedEvent.OutputObject>;

    filters: {
      
      'DisputeRaised(uint256,address)': TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
      DisputeRaised: TypedContractEvent<DisputeRaisedEvent.InputTuple, DisputeRaisedEvent.OutputTuple, DisputeRaisedEvent.OutputObject>;
    

      'DisputeResolved(uint256,uint256,uint256)': TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
      DisputeResolved: TypedContractEvent<DisputeResolvedEvent.InputTuple, DisputeResolvedEvent.OutputTuple, DisputeResolvedEvent.OutputObject>;
    

      'JobCancelled(uint256)': TypedContractEvent<JobCancelledEvent.InputTuple, JobCancelledEvent.OutputTuple, JobCancelledEvent.OutputObject>;
      JobCancelled: TypedContractEvent<JobCancelledEvent.InputTuple, JobCancelledEvent.OutputTuple, JobCancelledEvent.OutputObject>;
    

      'JobConcludedEarly(uint256,uint256)': TypedContractEvent<JobConcludedEarlyEvent.InputTuple, JobConcludedEarlyEvent.OutputTuple, JobConcludedEarlyEvent.OutputObject>;
      JobConcludedEarly: TypedContractEvent<JobConcludedEarlyEvent.InputTuple, JobConcludedEarlyEvent.OutputTuple, JobConcludedEarlyEvent.OutputObject>;
    

      'JobCreated(uint256,address,uint256,uint256)': TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
      JobCreated: TypedContractEvent<JobCreatedEvent.InputTuple, JobCreatedEvent.OutputTuple, JobCreatedEvent.OutputObject>;
    

      'MilestoneAdded(uint256,uint256,uint256)': TypedContractEvent<MilestoneAddedEvent.InputTuple, MilestoneAddedEvent.OutputTuple, MilestoneAddedEvent.OutputObject>;
      MilestoneAdded: TypedContractEvent<MilestoneAddedEvent.InputTuple, MilestoneAddedEvent.OutputTuple, MilestoneAddedEvent.OutputObject>;
    

      'MilestoneApproved(uint256,uint256,uint256)': TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
      MilestoneApproved: TypedContractEvent<MilestoneApprovedEvent.InputTuple, MilestoneApprovedEvent.OutputTuple, MilestoneApprovedEvent.OutputObject>;
    

      'TipSent(uint256,address,uint256)': TypedContractEvent<TipSentEvent.InputTuple, TipSentEvent.OutputTuple, TipSentEvent.OutputObject>;
      TipSent: TypedContractEvent<TipSentEvent.InputTuple, TipSentEvent.OutputTuple, TipSentEvent.OutputObject>;
    

      'WorkStarted(uint256,address)': TypedContractEvent<WorkStartedEvent.InputTuple, WorkStartedEvent.OutputTuple, WorkStartedEvent.OutputObject>;
      WorkStarted: TypedContractEvent<WorkStartedEvent.InputTuple, WorkStartedEvent.OutputTuple, WorkStartedEvent.OutputObject>;
    
    };
  }